using './main.bicep'

param environment = 'dev'
param applicationName = 'jobsite'
param location = 'eastus'
param vnetId = '/subscriptions/{subscriptionId}/resourceGroups/jobsite-core-rg/providers/Microsoft.Network/virtualNetworks/jobsite-vnet-dev'
param frontendSubnetId = '/subscriptions/{subscriptionId}/resourceGroups/jobsite-core-rg/providers/Microsoft.Network/virtualNetworks/jobsite-vnet-dev/subnets/snet-fe'
param dataSubnetId = '/subscriptions/{subscriptionId}/resourceGroups/jobsite-core-rg/providers/Microsoft.Network/virtualNetworks/jobsite-vnet-dev/subnets/snet-data'
param logAnalyticsWorkspaceId = '/subscriptions/{subscriptionId}/resourceGroups/jobsite-core-rg/providers/Microsoft.OperationalInsights/workspaces/jobsite-la-dev'
param keyVaultId = '/subscriptions/{subscriptionId}/resourceGroups/jobsite-core-rg/providers/Microsoft.KeyVault/vaults/jobsite-kv-dev'
param appGatewayCertSecretName = 'appgw-pfx-base64'
param appGatewayCertPasswordSecretName = 'appgw-pfx-password'
param vmssInstanceCount = 1
param sqlVmSize = 'Standard_D2s_v5'
param vmssVmSize = 'Standard_D2s_v5'
param sqlAdminUsername = 'jobsiteadmin'
param sqlAdminPassword = 'ChangeMe@123456'
param vmAdminUsername = 'azureuser'
param vmAdminPassword = 'ChangeMe@123456'
